tests/tools: use fork for multiprocessing.
The multiprocessing start method default was changed in Python 3.14
from "fork" to "forkserver".

This breaks our mock-patching. Change it back to "fork".

Fixes:

    ======================================================================
    FAIL: tests.test_cli.test_warning
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File ".../anorack/tests/tools.py", line 43, in test
        return f()
      File ".../anorack/tests/test_cli.py", line 157, in test_warning
        t(
        ~^
            stdin='A scratch?!',
            ^^^^^^^^^^^^^^^^^^^^
        ...<2 lines>...
            stderr_ipa="anorack: warning: can't determine correct article for 'scratch' /skɹˈatʃ/\n",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File ".../anorack/tests/test_cli.py", line 106, in t
        assert_equal(stderr, actual.stderr)
        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
    AssertionError: "anorack: warning: can't determine correct article for 'scratch' /skr'atS/\n" != ''

with Python 3.14.