anorack: add encoding declaration.
That way we can produce helpful error message when the program is
accidentally run against Python 2.X.

Before:

    $ python2.7 anorack
      File "anorack", line 3
    SyntaxError: Non-ASCII character '\xc2' in file anorack on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python2.7 anorack
    Traceback (most recent call last):
      File "anorack", line 30, in <module>
        import lib.cli  # pylint: disable=wrong-import-position
      File ".../lib/__init__.py", line 5
        type(...)  # Python >= 3 is required
             ^
    SyntaxError: invalid syntax